### ISSUE TITLE
Chapter26: Zend Framework: Bootstrapping

### ISSUE THREAD

**Issue by jeankobeis** [jeankobeis/phpmvc#127]
- [ ] [Why Zend Framework?](https://github.com/jeankobeis/phpmvc/issues/123)
- [ ] [Why Not Zend Framework?](https://github.com/jeankobeis/phpmvc/issues/124)
- [ ] [Getting Set Up](https://github.com/jeankobeis/phpmvc/issues/125)
- [ ] [Routes](https://github.com/jeankobeis/phpmvc/issues/126)
