### ISSUE TITLE
Chapter19: Extending

### ISSUE THREAD

**Issue by jeankobeis** [jeankobeis/phpmvc#98]
- [ ] [Foxy](https://github.com/jeankobeis/phpmvc/issues/88)
- [ ] [Custom CSS Fonts](https://github.com/jeankobeis/phpmvc/issues/89)
- [ ] [Building the Proxy](https://github.com/jeankobeis/phpmvc/issues/90)
- [ ] [Using the Proxy](https://github.com/jeankobeis/phpmvc/issues/91)
- [ ] [Imagine](https://github.com/jeankobeis/phpmvc/issues/92)
- [ ] [Observer](https://github.com/jeankobeis/phpmvc/issues/93)
- [ ] [Synchronicity](https://github.com/jeankobeis/phpmvc/issues/94)
- [ ] [Code](https://github.com/jeankobeis/phpmvc/issues/95)
- [ ] [Events](https://github.com/jeankobeis/phpmvc/issues/96)
- [ ] [Plugins](https://github.com/jeankobeis/phpmvc/issues/97)
